  - task: ArtifactoryDotnetCore@1
    inputs:
      command: 'restore'
      arguments: '-r linux-x64'
      artifactoryService: 'DavidArt'
      targetResolveRepo: 'nuget'
      rootPath: '$(Build.SourcesDirectory)/MyLogger/MyLogger.csproj'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'